stages:
  - build
  # - test
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build . -t problem-ui:latest
deploy:
  stage: deploy
  script:
    - cd /apps/problem && docker-compose up -d

